### ISSUE TITLE
在PC端如何从apk中获取UI树

### ISSUE THREAD

**Issue by zhangpeng23796** [AirtestProject/PocoService.apk#1]
网易开发这个功能非常流畅，比UIautomatorviewer要快的多，请问如果想在自己的程序里获取apk中的UI树信息（非 AirtestIDE或PocoHierarchyViewer ），该如何做？

**Comment by yimelia** [comment]
是指 [这个](https://poco-chinese.readthedocs.io/zh_CN/latest/index.html?highlight=dump#dump-ui-hierarchy-example) 么？

**Comment by zhangpeng23796** [comment]
这个需要依赖poco框架，可能略显重了。有没有可能自己直接通过IPC调用pocoservice.apk采集的ui树





在 yimelia <notifications@github.com>，2018年12月4日 20:45写道：

是指 这个<https://poco-chinese.readthedocs.io/zh_CN/latest/index.html?highlight=dump#dump-ui-hierarchy-example> 么？

**Comment by adolli** [comment]
@zhangpeng23796 pocoservice(pocoservice.apk)本身有提供RPC接口，但是这个RPC是建立在内部poco自己的协议上的，不建议直接使用RPC。如果要直接调用RPC，可以使用已经封装好的agent类。第一个参数传设备的ip地址+10081端口，但是需要自己手动把pocoservice这个Instrumentation test启动起来。
```py
import json
from poco.drivers.android.uiautomation import AndroidPocoAgent

agent = AndroidPocoAgent("http://{DEVICE_IP}:10081", None)
ui = agent.hierarchy.dump()
print(json.dumps(ui, indent=4))
```

**Comment by zhangpeng23796** [comment]
@adolli ，多谢，我试试
