### ISSUE TITLE
频繁crash

### ISSUE THREAD

**Issue by StevenXUzw** [AirtestProject/PocoService.apk#2]
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'

在哪里获取crash的日志

**Comment by kevenfeng** [comment]
me too

**Comment by MLL1228** [comment]
请问有什么解决办法吗？

**Comment by michaelwugit** [comment]
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.

**Comment by yimelia** [comment]
检查是否pocoservice被手机限制了自启动和后台，比如华为和一加：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_6

https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_8

**Comment by Zz3y** [comment]
> 检查是否pocoservice被手机限制了自启动和后台，比如华为和一加：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_6
> 
> https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_8

检查了，所有能去掉的限制都去掉了，还是无法保证的出现crash

**Comment by zhiqiangren** [comment]
我也是会出现，出现时机不清楚，每次运行总会在某个Case出现几个这个提示

**Comment by zhiqiangren** [comment]
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''

这种出现好像不影响脚本，就是屏幕会刷一下。

[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
这种出现Case就会失败

手机型号是：vivo X21A

uiautomator2  2.11.2
pocounit 1.0.40
pocoui  1.0.85
airtest   1.2.4
